---
abstract: 'Experimental enhancements to MetaConfig'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0.89'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.041, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-MetaConfig-Deep
provides:
  Dist::Zilla::Plugin::MetaConfig::Deep:
    file: lib/Dist/Zilla/Plugin/MetaConfig/Deep.pm
    version: '0.001001'
recommends:
  Moose: '2.000'
requires:
  Dist::Zilla::Role::MetaProvider: '0'
  Moose: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Dist-Zilla-Plugin-MetaConfig-Deep/issues
  homepage: https://github.com/kentnl/Dist-Zilla-Plugin-MetaConfig-Deep
  repository: https://github.com/kentnl/Dist-Zilla-Plugin-MetaConfig-Deep.git
version: '0.001001'
